name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-13  # macOS with Xcode 15.0 by default

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select latest Xcode
        run: |
          sudo xcode-select -s "/Applications/Xcode_15.0.app"

      - name: Build and Test
        run: |
          xcodebuild clean test \
            -project Calculator.xcodeproj \
            -scheme Calculator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
