name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensures full Git history

    # 🔧 ADD THE PROJECT REPAIR STEP HERE (BEFORE BUILDING)
    - name: Repair Project File (if corrupted)
      run: |
        git checkout HEAD -- Calculator.xcodeproj || true
        rm -rf ~/Library/Developer/Xcode/DerivedData/*

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    - name: Show Xcode version (debugging)
      run: xcodebuild -version

    - name: List schemes (debugging)
      run: xcodebuild -list -project Calculator.xcodeproj

    - name: Build and Test
      run: |
        xcodebuild clean test \
          -project Calculator.xcodeproj \
          -scheme Calculator \
          -destination "platform=iOS Simulator,name=iPhone 14" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          ENABLE_TESTABILITY=YES \
          | xcpretty && exit ${PIPESTATUS[0]}
