name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    - name: Build and Test
      run: |
        xcodebuild clean test \
        -project Calculator.xcodeproj \
        -scheme Calculator \
        -destination "platform=iOS Simulator,name=iPhone 14"



